Repository StreetArtMap/streetArtMap, pull requests merged in 2020-09, with the labels that each got.

#19 Feature/navigation
  src/UIComponents/Header/Header.js
  src/UIComponents/Layout/Layout.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Nav/Nav.js
  src/containers/App/App.js
  src/pages/CreatePage/CreatePage.js
  src/pages/ExplorePage/ExplorePage.js
  src/pages/LoginPage/LoginPage.js
  src/pages/MapPage/MapPage.js
  src/pages/ProfilePage/ProfilePage.js
Labels: Front End, enhancement

#20 Install proptypes, created reusable ui for button + input, sketch lay…
  package.json
  src/UIComponents/Button/Button.js
  src/UIComponents/Header/Header.js
  src/UIComponents/Input/Input.js
  src/components/App/App.js
  src/components/Nav/Nav.js
  src/index.js
  src/pages/LoginPage/LoginPage.css
  src/pages/LoginPage/LoginPage.js
Labels: Front End, check-in 2, enhancement

#21 Feature/createart
  package-lock.json
  package.json
  public/index.html
  src/UIComponents/Button/Button.css
  src/UIComponents/Button/Button.js
  src/UIComponents/Input/Input.css
  src/UIComponents/Input/Input.js
  src/UIComponents/LoadingSpinner/LoadingSpinner.css
  src/UIComponents/LoadingSpinner/LoadingSpinner.js
  src/components/App/App.js
  src/components/Camera/Camera.css
  src/components/Camera/Camera.js
  src/components/Camera/webcam.js
  src/components/CreateForm/CreateForm.js
  src/components/ImageUpload/ImageUpload.js
  src/pages/CameraPage/CameraPage.js
  src/pages/CreatePage/CreatePage.js
  src/pages/LoginPage/LoginPage.css
  src/pages/LoginPage/LoginPage.js
Labels: Front End, check-in 2, enhancement

#22 Feature/header and nav
  package-lock.json
  package.json
  src/UIComponents/Header/Header.css
  src/UIComponents/Header/Header.js
  src/UIComponents/Input/Input.css
  src/UIComponents/Layout/Layout.css
  src/UIComponents/Layout/Layout.js
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Camera/Camera.css
  src/components/Camera/Camera.js
  src/components/CreateForm/CreateForm.js
  src/components/ImageUpload/ImageUpload.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/pages/CameraPage/CameraPage.css
  src/pages/CameraPage/CameraPage.js
  src/pages/ExplorePage/ExplorePage.css
  src/pages/ExplorePage/ExplorePage.js
  src/pages/LoginPage/LoginPage.js
  src/pages/LoginPage/LoginPage.test.js
  src/pages/MapPage/MapPage.css
  src/pages/MapPage/MapPage.js
  src/pages/ProfilePage/ProfilePage.css
  src/pages/ProfilePage/ProfilePage.js
  src/reducers/userReducer.js
Labels: Front End, check-in 2, enhancement

#25 Feature/artupload
  .gitignore
  package-lock.json
  package.json
  src/MOCK_DATA.js
  src/components/App/App.js
  src/components/Camera/Camera.js
  src/components/CreateForm/CreateForm.js
  src/components/MapWithMarkers/MapWithMarkers.css
  src/components/MapWithMarkers/MapWithWithMarkers.js
  src/components/MapWithNavigation/MapWithNavigation.css
  src/components/MapWithNavigation/MapWithNavigation.js
  src/components/MapWithNavigation/mapWithNavigationStyle.js
  src/components/Nav/Nav.js
  src/pages/MapPage/MapPage.css
  src/pages/MapPage/MapPage.js
Labels: Front End, check-in 2, enhancement

#27 Feature/explore
  package-lock.json
  package.json
  src/UIComponents/Button/Button.css
  src/UIComponents/Button/Button.js
  src/UIComponents/Header/Header.css
  src/UIComponents/Header/Header.js
  src/UIComponents/Input/Input.css
  src/UIComponents/ScrollHide/ScrollHide.js
  src/components/App/App.css
  src/components/ArtContainer/ArtContainer.css
  src/components/ArtContainer/ArtContainer.js
  src/components/ArtDetails/ArtDetails.css
  src/components/ArtDetails/ArtDetails.js
  src/components/Camera/Camera.css
  src/components/Camera/Camera.js
  src/components/CreateForm/CreateForm.css
  src/components/CreateForm/CreateForm.js
  src/components/ImageCarousel/ImageCarousel.css
  src/components/ImageCarousel/ImageCarousel.js
  src/components/ImageUpload/ImageUpload.css
  src/components/ImageUpload/ImageUpload.js
  src/components/MapWithMarkers/MapWithMarkers.css
  src/components/MapWithMarkers/MapWithWithMarkers.js
  src/components/MapWithNavigation/MapWithNavigation.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/index.css
  src/pages/CameraPage/CameraPage.css
  src/pages/CameraPage/CameraPage.js
  src/pages/ExplorePage/ExplorePage.css
  src/pages/ExplorePage/ExplorePage.js
  src/pages/LoginPage/LoginPage.css
  src/pages/LoginPage/LoginPage.js
  src/pages/MapPage/MapPage.css
  src/pages/ProfilePage/ProfilePage.css
  src/reducers/artsReducer.js
  src/reducers/index.js
  src/reducers/userReducer.js
  src/variables.css
Labels: Front End, enhancement

#30 Feature/createform
  src/UIComponents/Input/Input.css
  src/UIComponents/Input/Input.js
  src/components/Camera/Camera.js
  src/components/CreateForm/CreateForm.css
  src/components/CreateForm/CreateForm.js
  src/components/ImageCarousel/ImageCarousel.js
  src/components/ImageUpload/ImageUpload.js
  src/constants.js
  src/pages/CameraPage/CameraPage.js
  src/variables.css
Labels: Front End, enhancement

#31 Feature/profile
  src/components/App/matchMediaMock.js
  src/components/Camera/Camera.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.test.js
  src/pages/CameraPage/CameraPage.css
  src/pages/ExplorePage/ExplorePage.test.js
  src/pages/ProfilePage/ProfilePage.css
  src/pages/ProfilePage/ProfilePage.js
  src/pages/ProfilePage/ProfilePage.test.js
Labels: Front End, enhancement

#32 Feature/networkrequests
  package-lock.json
  package.json
  src/UIComponents/Header/Header.css
  src/UIComponents/LoadingSpinner/LoadingSpinner.css
  src/components/Camera/Camera.js
  src/components/CreateForm/CreateForm.css
  src/components/CreateForm/CreateForm.js
  src/components/MapWithMarkers/MapWithMarkers.css
  src/components/MapWithMarkers/MapWithWithMarkers.js
  src/components/Nav/Nav.css
  src/index.js
  src/pages/CameraPage/CameraPage.js
  src/pages/ExplorePage/ExplorePage.test.js
  src/setupTests.js
Labels: Front End, enhancement

#34 Feature/apollo setup
  src/actions/userAction.js
  src/components/App/App.js
  src/components/CreateForm/CreateForm.js
  src/components/ImageCarousel/ImageCarousel.js
  src/components/MapWithMarkers/MapWithWithMarkers.js
  src/index.js
  src/pages/LoginPage/LoginPage.js
  src/pages/LoginPage/LoginPage.test.js
  src/pages/ProfilePage/ProfilePage.css
  src/pages/ProfilePage/ProfilePage.js
  src/reducers/artsReducer.js
  src/reducers/reducers.test.js
  src/reducers/userReducer.js
Labels: Front End, check-in 2, enhancement

#44 Feature/datamanipulation
  src/UIComponents/LoadingSpinner/LoadingSpinner.js
  src/actions/userAction.js
  src/components/App/App.js
  src/components/ArtContainer/ArtContainer.js
  src/components/ArtDetails/ArtDetails.js
  src/components/Camera/Camera.js
  src/components/CreateForm/CreateForm.js
  src/components/ImageCarousel/ImageCarousel.js
  src/components/ImageUpload/ImageUpload.js
  src/components/MapWithMarkers/MapWithWithMarkers.js
  src/constants.js
  src/index.js
  src/pages/LoginPage/LoginPage.js
  src/pages/ProfilePage/ProfilePage.js
  src/reducers/artsReducer.js
  src/reducers/userReducer.js
  src/variables.css
Labels: Front End, enhancement

#47 Fix test suite for travis ci
  src/pages/ExplorePage/ExplorePage.test.js
Labels: Front End

#53 Add eslint ignore comments
  src/UIComponents/ScrollHide/ScrollHide.js
  src/components/App/App.js
  src/components/ArtDetails/ArtDetails.js
  src/components/Camera/Camera.js
  src/components/CreateForm/CreateForm.js
  src/components/MapWithMarkers/MapWithWithMarkers.js
  src/pages/ExplorePage/ExplorePage.js
  src/pages/LoginPage/LoginPage.js
Labels: Front End, MVP, enhancement

#62 Feature/detailing
  src/UIComponents/Input/Input.js
  src/UIComponents/Layout/Layout.js
  src/components/App/App.js
  src/components/Camera/Camera.js
  src/components/MapWithNavigation/MapWithNavigation.js
  src/pages/ExplorePage/ExplorePage.js
  src/pages/LoginPage/LoginPage.css
  src/pages/LoginPage/LoginPage.js
Labels: Front End, enhancement

#71 Feature/user details
  README.md
  src/components/ArtDetails/ArtDetails.js
  src/components/CreateForm/CreateForm.js
  src/components/ImageCarousel/ImageCarousel.js
  src/components/Nav/Nav.css
  src/components/PaintingCard/PaintingCard.js
  src/constants.js
  src/pages/LoginPage/LoginPage.js
  src/pages/ProfilePage/ProfilePage.css
  src/pages/ProfilePage/ProfilePage.js
Labels: Front End, MVP

#76 Feature/tests
  package-lock.json
  package.json
  src/UIComponents/Button/Button.js
  src/UIComponents/Input/Input.js
  src/UIComponents/Layout/Layout.js
  src/UIComponents/LoadingSpinner/LoadingSpinner.js
  src/UIComponents/Modal/Modal.js
  src/components/ArtContainer/ArtContainer.js
  src/components/ArtDetails/ArtDetails.js
  src/components/Camera/Camera.js
  src/components/CreateForm/CreateForm.EDITtest.js
  src/components/CreateForm/CreateForm.js
  src/components/ImageCarousel/ImageCarousel.js
  src/components/ImageUpload/ImageUpload.js
  src/components/MapWithMarkers/MapWithWithMarkers.js
  src/pages/CameraPage/CameraPage.test.js
  src/pages/ExplorePage/ExplorePage.test.js
  src/pages/LoginPage/LoginPage.css
  src/pages/LoginPage/LoginPage.js
  src/pages/ProfilePage/ProfilePage.css
  src/pages/ProfilePage/ProfilePage.js
  src/pages/ProfilePage/ProfilePage.test.js
Labels: Front End, MVP

#81 Fix endpoint for tours and adjust spinner for tours modal and change …
  src/UIComponents/LoadingSpinner/LoadingSpinner.css
  src/UIComponents/Modal/Modal.css
  src/components/MapWithMarkers/MapWithMarkers.css
  src/components/Nav/Nav.js
  src/pages/MapPage/MapPage.js
  src/serviceworker.js
  src/sw.js
  src/sw.js.map
  src/workbox-9f2a03dc.js
  src/workbox-9f2a03dc.js.map
  workbox-config.js
Labels: Front End, enhancement
